# Generated by Django 3.2.16 on 2023-02-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userType',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
