# Generated by Django 3.2.16 on 2023-02-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='staff',
        ),
    ]
