# Generated by Django 3.2.16 on 2023-05-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230523_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_admin',
            new_name='admin',
        ),
    ]
