# Generated by Django 3.2.16 on 2023-02-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20230212_2308'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apploved',
            name='applouved_unique',
        ),
        migrations.AddConstraint(
            model_name='apploved',
            constraint=models.UniqueConstraint(fields=('applouved_user', 'group'), name='applouved_unique'),
        ),
    ]
