# Generated by Django 3.2.16 on 2023-02-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20230219_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='group',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
