# Generated by Django 3.2.16 on 2023-02-19 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0011_event_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apploved',
            new_name='Approved',
        ),
        migrations.RemoveConstraint(
            model_name='approved',
            name='applouved_unique',
        ),
        migrations.RenameField(
            model_name='approved',
            old_name='applouved',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='approved',
            old_name='applouved_user',
            new_name='approved_user',
        ),
        migrations.AddConstraint(
            model_name='approved',
            constraint=models.UniqueConstraint(fields=('approved_user', 'group'), name='approved_unique'),
        ),
    ]
