# Generated by Django 3.2.16 on 2023-02-23 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230211_0942'),
        ('reservation', '0013_auto_20230221_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_user', to='accounts.staffuser'),
            preserve_default=False,
        ),
    ]
