# Generated by Django 3.2.16 on 2023-02-23 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0014_group_group_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Approved',
            new_name='ApprovedMember',
        ),
        migrations.RemoveConstraint(
            model_name='approvedmember',
            name='approved_unique',
        ),
        migrations.RenameField(
            model_name='approvedmember',
            old_name='approved_user',
            new_name='approved_member',
        ),
        migrations.AddConstraint(
            model_name='approvedmember',
            constraint=models.UniqueConstraint(fields=('approved_member', 'group'), name='approved_unique'),
        ),
    ]
