# Generated by Django 3.2.16 on 2023-02-23 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0018_alter_approvedstaff_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applying', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applying', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.group')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Applying',
        ),
        migrations.AddConstraint(
            model_name='applyingstaff',
            constraint=models.UniqueConstraint(fields=('staff', 'group'), name='appliyng_staff_unique'),
        ),
        migrations.AddConstraint(
            model_name='applyingmember',
            constraint=models.UniqueConstraint(fields=('member', 'group'), name='appliyng_member_unique'),
        ),
    ]
