# Generated by Django 3.2.16 on 2023-02-26 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0019_auto_20230224_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join', models.BooleanField(default=False)),
                ('join_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.event')),
                ('join_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='join',
            constraint=models.UniqueConstraint(fields=('join_name', 'join_event'), name='join_unique'),
        ),
    ]
