# Generated by Django 3.2.16 on 2023-02-12 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applying', models.BooleanField(default=False)),
                ('applying_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservation.group')),
                ('applying_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='applying',
            constraint=models.UniqueConstraint(fields=('applying_user', 'applying_group'), name='appliyng_unique'),
        ),
    ]
