# Generated by Django 3.2.16 on 2023-02-12 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0004_auto_20230212_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apploved',
            name='applouved_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apploved',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.group'),
        ),
        migrations.AlterField(
            model_name='applying',
            name='applying_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applying_group', to='reservation.group'),
        ),
        migrations.AlterField(
            model_name='applying',
            name='applying_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applying_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
