# Generated by Django 3.2.16 on 2023-02-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20230213_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.event'),
        ),
    ]
