# Generated by Django 3.2.16 on 2023-02-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_group_group_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_event',
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation.group'),
            preserve_default=False,
        ),
    ]
