# Generated by Django 3.2.16 on 2023-02-23 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0016_auto_20230223_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedstaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
