# Generated by Django 3.2.16 on 2024-10-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0021_auto_20230303_0053'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='join',
            name='join_unique',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('event_title', 'event_date', 'start_time', 'end_time'), name='event_unique'),
        ),
    ]
